version:    1
disable_existing_loggers:    False

formatters:
    default:
            format:     "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
            datefmt:    '%Y/%m/%d %I:%M:%S %p'yes

filters:
    trace_filter:
            ():         boopit.logging.logging_filters.LevelFilter
            level:      5

    no_pymongo_topology_filter:
            ():         boopit.logging.logging_filters.NoPymongoTopologyFilter
            name:       pymongo.topology

handlers:
    console:
            class:      logging.StreamHandler
            formatter:  default
            level:      DEBUG
            stream:     ext://sys.stdout
            filters:
                - no_pymongo_topology_filter
    trace:
            class:      logging.FileHandler
            filename:   chelexicon/logging/logs/trace.log
            level:      TRACE
            formatter:  default
            errors:     ignore
            filters:
                - trace_filter
    error:
            class:      logging.FileHandler
            filename:   chelexicon/logging/logs/error.log
            level:      ERROR
            formatter:  default
            errors:     ignore
    debug:
            class:      logging.FileHandler
            filename:   chelexicon/logging/logs/debug.log
            level:      DEBUG
            formatter:  default
            errors:     ignore
            filters:
                - no_pymongo_topology_filter

    urllib:
            class:      logging.FileHandler
            filename:   chelexicon/logging/logs//urllib.log
            level:      DEBUG
            formatter:  default
            errors:     ignore

    pymongo:
            class:      logging.FileHandler
            filename:   chelexicon/logging/logs/pymongo.log
            level:      DEBUG
            formatter:  default
            errors:     ignore
loggers:
    '':
            level:          DEBUG
            handlers:   [error, debug, trace, console]

    'urllib3':
            level:      DEBUG
            handlers:   [urllib]

    'pymongo':
            level:      DEBUG
            handlers:   [pymongo]